name: "Setup Flutter Environment"
description: "Set up Flutter environment for the project"

inputs:
  runner:
    description: "The runner environment to use (e.g., ubuntu-latest, macos-latest)"
    required: true
  supabase_url:
    description: "Supabase URL"
    required: true
  supabase_key:
    description: "Supabase Key"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Create .env file
      run: |
        echo "REACT_APP_SUPABASE_URL=${{ inputs.supabase_url }}" >> admin/flutter_application/.env
        echo "REACT_APP_SUPABASE_KEY=${{ inputs.supabase_key }}" >> admin/flutter_application/.env
      shell: bash

    - name: Cache Flutter dependencies
      uses: actions/cache@v4
      with:
        path: ~/.pub-cache
        key: flutter-pub-cache-${{ inputs.runner }}-${{ hashFiles('**/pubspec.yaml') }}
        restore-keys: |
          flutter-pub-cache-${{ inputs.runner }}

    - name: Install dependencies
      run: |
        cd admin/flutter_application
        flutter pub get
      shell: bash