name: Flutter CI

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: macos-latest # Use macOS for iOS-related steps
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install dependencies
        run: |
          cd admin/flutter_application
          flutter pub get

      - name: Boot iOS Simulator
        run: |
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          xcrun simctl list devices
          xcrun simctl boot "iPhone 14" # Use a valid device name for the iOS Simulator
          xcrun simctl bootstatus

      - name: Run tests
        run: |
          cd admin/flutter_application
          flutter test integration_test