name: Flutter CI

on:
  push:
    branches:
      - master

env:
  REACT_APP_SUPABASE_URL: ${{ secrets.REACT_APP_SUPABASE_URL }}
  REACT_APP_SUPABASE_KEY: ${{ secrets.REACT_APP_SUPABASE_KEY }}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # Create the .env file
      - name: Create .env file
        run: |
          echo "REACT_APP_SUPABASE_URL=${{ secrets.REACT_APP_SUPABASE_URL }}" >> admin/flutter_application/.env
          echo "REACT_APP_SUPABASE_KEY=${{ secrets.REACT_APP_SUPABASE_KEY }}" >> admin/flutter_application/.env

      # Cache dependencies
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: flutter-pub-cache-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            flutter-pub-cache-${{ runner.os }}

      # Install dependencies
      - name: Install dependencies
        run: |
          cd admin/flutter_application
          flutter pub get

  build-android:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # Create the .env file
      - name: Create .env file
        run: |
          echo "REACT_APP_SUPABASE_URL=${{ secrets.REACT_APP_SUPABASE_URL }}" >> admin/flutter_application/.env
          echo "REACT_APP_SUPABASE_KEY=${{ secrets.REACT_APP_SUPABASE_KEY }}" >> admin/flutter_application/.env

      # Build Android app
      - name: Build Android APK
        run: |
          cd admin/flutter_application
          flutter build apk --release

      # Upload APK as an artifact
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-app
          path: admin/flutter_application/build/app/outputs/flutter-apk/admin-app-release.apk