name: Playwright Testing on Vercel Deployment

on:
  push:
    branches:
      - master

env:
  CI: true
  BASE_URL: ${{ vars.BASE_URL }}
  REACT_APP_SUPABASE_URL: ${{ secrets.REACT_APP_SUPABASE_URL }}
  REACT_APP_SUPABASE_KEY: ${{ secrets.REACT_APP_SUPABASE_KEY }}
  TESULTS_TARGET_PLAYWRIGHT: ${{ secrets.TESULTS_TARGET_PLAYWRIGHT }}

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1/4, 2/4, 3/4, 4/4]
        test-type: [unit, integration, e2e]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run ${{ matrix.test-type }} Tests
        run: npx playwright test src/tests/${{ matrix.test-type }} --shard ${{ matrix.shard }}

      - name: Upload Test Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.test-type }}-test-report
          path: playwright-report
          retention-days: 30

      - name: Generate Test Summary
        if: always()
        run: |
          echo "### Test Results for ${{ matrix.test-type }}" >> $GITHUB_STEP_SUMMARY
          echo "- Shard: ${{ matrix.shard }}" >> $GITHUB_STEP_SUMMARY