name: Playwright Testing on Vercel Deployment

on:
  push:
    branches:
      - master

jobs:
  integration-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Integration Tests
        run: npm run test:integration
        env:
          CI: true
          BASE_URL: ${{ vars.BASE_URL }}

      - name: Upload Integration Test Report (if tests fail)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-report
          path: playwright-report
          retention-days: 30

  e2e-tests:
    needs: integration-tests
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run E2E Tests
        run: npm run test:e2e
        env:
          CI: true
          BASE_URL: ${{ vars.BASE_URL }}

      - name: Upload E2E Test Report (if tests fail)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-report
          path: playwright-report
          retention-days: 30