name: Playwright Testing on Vercel Deployment

on:
  push:
    branches:
      - master

jobs:
  wait-for-vercel-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Vercel Deployment to Complete
        id: get-url
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          # Poll Vercel API to check deployment status
          while true; do
            DEPLOYMENT_URL=$(curl -s -H "Authorization: Bearer $VERCEL_TOKEN" \
              "https://api.vercel.com/v6/deployments?projectId=$VERCEL_PROJECT_ID&state=READY" \
              | jq -r '.deployments[0].url')

            if [ "$DEPLOYMENT_URL" != "null" ]; then
              echo "Deployment URL: $DEPLOYMENT_URL"
              # Use environment file to set output
              echo "deployment_url=https://$DEPLOYMENT_URL" >> $GITHUB_ENV
              break
            fi

            echo "Waiting for Vercel deployment to be ready..."
            sleep 10
          done

  test:
    runs-on: ubuntu-latest
    needs: wait-for-vercel-deployment
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Playwright Tests
        run: npx playwright test
        env:
          CI: true
          BASE_URL: ${{ env.deployment_url }}

      - name: Upload Playwright Report (if tests fail)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 30